"""Generate the plate library: real plate solids from published dimensions.

These are **generic** plates. No manufacturer CAD is used, referenced or
implied, and every catalogue entry says so. What they are is dimensionally
faithful to the published classes they are drawn from — thickness, width,
hole pitch, screw seat, notch — with the construction real plates use:

* a bar with straight parallel edges and rounded ends, not a chain of washers;
* small circular notches in both edges between holes, where the plate is meant
  to bend (miniplates: notches so deep the plate is eyelets on thin bars);
* conical screw seats, and on locking plates a conical thread in the seat,
  drawn as rings at the thread pitch rather than a helix;
* a rounded edge break on the outline;
* preformed plates curved the way they sit on the jaw: body curvature through
  the plate's thickness, the gonial angle turn in the plate's own plane.

The faces are meshed with a fine constrained Delaunay triangulation so that no
edge along the plate exceeds about a millimetre. A coarse face mesh has long
triangles spanning several holes, and when such a plate is bent each triangle
stays flat: a chord across a curved plate.

This is a build tool and may use VTK; it makes no network calls.

    python3 tools/make_plate_assets.py

Writes binary PLY meshes and ``plates.json`` into ``mandiplan/data/plates``.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import vtk
from vtkmodules.util.numpy_support import numpy_to_vtk, vtk_to_numpy

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mandiplan.geometry.mesh_io import Mesh, orient_outward  # noqa: E402
from mandiplan.geometry.plate_bend import bend_to_path  # noqa: E402
from mandiplan.geometry.plate_profile import (  # noqa: E402
    HoleSpec,
    NotchSpec,
    PlateShape,
    hole_loop,
    marking_slots,
    outline,
    point_in_polygon,
)

OUT_DIR = ROOT / "mandiplan" / "data" / "plates"
HOLE_SAMPLES = 32
FACE_GRID_MM = (0.6, 0.75)

GENERIC_NOTICE = (
    "Generic parametric approximation - not manufacturer-specific and not for "
    "clinical device selection."
)
PROVENANCE = (
    "Generated by tools/make_plate_assets.py in this repository from published "
    "dimensional classes of reconstruction plates and miniplates (see "
    "dimension_sources). No manufacturer CAD, drawing or part geometry was used."
)
LICENCE = "CC0-1.0 (generated in-repo; no third-party rights)"


@dataclass(frozen=True)
class Section:
    """The cross-section and hole of a plate class."""

    thickness_mm: float
    width_mm: float
    pitch_mm: float
    hole: HoleSpec
    notch: NotchSpec
    edge_radius_mm: float = 0.3


@dataclass
class Family:
    family: str
    name: str
    category: str
    section: Section
    #: (asset suffix, hole x positions) for each length made.
    layouts: list[tuple[str, tuple[float, ...]]]
    material_id: str
    load_bearing: bool
    sources: tuple[str, ...]
    notes: str
    min_bend_radius_mm: float = 12.0
    #: Leave unset to derive it from the section and the alloy; see
    #: :func:`working_bend_limit`.
    max_bend_deg_per_node: float | None = None
    #: Per-gap notch overrides, e.g. the long bridge of a bridged miniplate.
    gap_notches: dict[int, NotchSpec] = field(default_factory=dict)
    #: Preform program: ("arch", from_hole, to_hole, degrees) curls the plate
    #: through its thickness toward the bone; ("turn", from_hole, to_hole,
    #: degrees) turns it in its own plane.
    preform: tuple[tuple[str, int, int, float], ...] = ()
    marking: tuple[str, ...] = ()
    code: str = ""


def working_bend_limit(section: Section, pitch_mm: float, material_id: str) -> float:
    """Largest bend one bridge between two holes can take, in degrees.

    The bend is made over the bridge between two screw seats, so its radius
    is at least the bridge length over the angle. The outer fibre strain of a
    bend of radius R in a plate of thickness t is t / (2R + t); keeping it to
    80% of the alloy's rated elongation, and no tighter than the alloy's own
    minimum bend radius, gives the smallest radius, and the bridge length
    over that radius is the angle. For a 2.4 mm grade 4 plate on an 8 mm
    pitch that is about 26°: the chin, some 20° a pitch, is inside it.
    """
    from mandiplan.materials import alloy_by_id

    alloy = alloy_by_id(material_id)
    t = section.thickness_mm
    allowed = 0.8 * alloy.elongation_pct / 100.0
    radius = max(alloy.min_bend_radius_mm(t), t * (1.0 - allowed) / (2.0 * allowed))
    bridge = max(pitch_mm - section.hole.seat_diameter_mm, 0.5)
    return float(min(math.floor(math.degrees(bridge / radius)), 45.0))


def evenly(count: int, pitch: float) -> tuple[float, ...]:
    return tuple(float(i * pitch) for i in range(count))


LOCK_24 = Section(2.5, 8.0, 8.0, HoleSpec(2.5, 4.2, locking=True), NotchSpec(0.9, 2.9))
LP_24 = Section(2.4, 8.0, 8.0, HoleSpec(2.5, 4.0), NotchSpec(0.9, 2.9))
HEAVY_28 = Section(2.8, 10.0, 9.0, HoleSpec(2.8, 5.0, locking=True), NotchSpec(1.1, 3.4))
PRIMARY_15 = Section(1.5, 6.0, 7.0, HoleSpec(2.1, 3.4, seat_depth_fraction=0.6), NotchSpec(0.8, 2.6), 0.25)
MINI_20 = Section(1.0, 4.3, 6.0, HoleSpec(2.1, 3.1, seat_depth_fraction=0.6), NotchSpec(1.05, 4.4), 0.15)

SRC_LP = (
    "Conventional low-profile 2.4 mm reconstruction plate modelled at "
    "135 x 8 x 2.4 mm (finite element study of low-profile reconstruction "
    "plates for the atrophic mandible)."
)
SRC_LOCK = (
    "Locking reconstruction plate 2.4: plate thickness 2.5 mm, 2.4 and 3.0 mm "
    "locking screws in threaded holes (AO Foundation approved-solution "
    "description of the system)."
)
SRC_NOTCH = (
    "Reconstruction plates carry notches between screw holes so that they "
    "bend between holes rather than through them (AO technique teaching)."
)
SRC_PITCH = (
    "Generic round-hole reconstruction plates listed at 62 mm for 8 holes up "
    "to 188 mm for 24 holes, i.e. about 8 mm per hole."
)
SRC_HEAVY = (
    "Precontoured and straight reconstruction plates at 2.8 mm profile height "
    "(11-hole straight; hemimandibular 5 + 17 holes; full mandibular "
    "6 + 13 + 6 holes); heavy reconstruction plate widths of about 10 mm in "
    "published catalogues."
)
SRC_PRIMARY = (
    "Small reconstruction plates at 1.5 mm, for primary reconstruction with a "
    "vascularised bone graft and not load-bearing; primary reconstruction "
    "plates in 11- and 17-hole lengths at 1.5 mm profile."
)
SRC_MINI = (
    "2.0 mm 4-hole titanium miniplate modelled at 26 mm length, 4.3 mm width, "
    "1.0 mm thickness (finite element studies of mandibular fracture "
    "fixation); miniplate hole distance 6 mm."
)

FAMILIES: tuple[Family, ...] = (
    Family(
        family="generic-recon-2.4-lp",
        name="Low-profile reconstruction plate 2.4, straight",
        category="reconstruction bar",
        section=LP_24,
        layouts=[(f"{n}h", evenly(n, 8.0)) for n in (8, 12, 17, 24)],
        material_id="cp-ti-grade-4",
        load_bearing=True,
        sources=(SRC_LP, SRC_PITCH, SRC_NOTCH),
        notes="Load-bearing bar for a segmental defect. Non-locking conical seats.",
        marking=("Ti4", "2.4", "LP"),
        code="LP24",
    ),
    Family(
        family="generic-recon-2.4-lock",
        name="Locking reconstruction plate 2.4, straight",
        category="reconstruction bar",
        section=LOCK_24,
        layouts=[(f"{n}h", evenly(n, 8.0)) for n in (10, 16, 20)],
        material_id="cp-ti-grade-4",
        load_bearing=True,
        sources=(SRC_LOCK, SRC_PITCH, SRC_NOTCH),
        notes=(
            "Threaded conical holes take locking screws; fit bending insets in "
            "any hole meant for a locking screw before contouring."
        ),
        marking=("Ti4", "2.4", "LCK"),
        code="LK24",
    ),
    Family(
        family="generic-recon-2.8",
        name="Heavy reconstruction plate, 2.8 mm profile, straight",
        category="reconstruction bar",
        section=HEAVY_28,
        layouts=[(f"{n}h", evenly(n, 9.0)) for n in (11, 17)],
        material_id="cp-ti-grade-4",
        load_bearing=True,
        sources=(SRC_HEAVY, SRC_NOTCH),
        min_bend_radius_mm=15.0,
        notes="Stiff bar for a long defect or a poor bone bed; shape by press.",
        marking=("Ti4", "2.8", "HVY"),
        code="HV28",
    ),
    Family(
        family="generic-recon-1.5-primary",
        name="Primary reconstruction plate 1.5, straight",
        category="primary reconstruction",
        section=PRIMARY_15,
        layouts=[(f"{n}h", evenly(n, 7.0)) for n in (11, 17)],
        material_id="cp-ti-grade-4",
        load_bearing=False,
        sources=(SRC_PRIMARY, SRC_NOTCH),
        min_bend_radius_mm=6.0,
        notes=(
            "NOT load-bearing. Holds a vascularised bone graft in place; it "
            "does not carry the mandible across a defect on its own."
        ),
        marking=("Ti4", "1.5"),
        code="PR15",
    ),
    Family(
        family="generic-miniplate-2.0",
        name="Miniplate 2.0",
        category="miniplate",
        section=MINI_20,
        layouts=[
            ("4h", evenly(4, 6.0)),
            ("4h-bridge", (0.0, 6.0, 16.0, 22.0)),
            ("6h", evenly(6, 6.0)),
            ("8h", evenly(8, 6.0)),
        ],
        gap_notches={},
        material_id="cp-ti-grade-2",
        load_bearing=False,
        sources=(SRC_MINI,),
        min_bend_radius_mm=4.0,
        notes=(
            "NOT load-bearing. Fracture and osteotomy fixation along Champy's "
            "lines. Too narrow to carry an etched mark."
        ),
        code="MN20",
    ),
    Family(
        family="generic-recon-2.4-body",
        name="Locking reconstruction plate 2.4, preformed body curve",
        category="mandibular body",
        section=LOCK_24,
        layouts=[(f"{n}h", evenly(n, 8.0)) for n in (12, 16)],
        preform=(("arch", 1, -2, 35.0),),
        material_id="cp-ti-grade-4",
        load_bearing=True,
        sources=(SRC_LOCK, SRC_NOTCH),
        notes=(
            "Curved 35 degrees through its thickness, the way the lateral "
            "surface of the body curves; the bone face is the concave one."
        ),
        marking=("Ti4", "2.4", "BDY"),
        code="BD24",
    ),
    Family(
        family="generic-recon-2.4-angle",
        name="Locking reconstruction plate 2.4, preformed angle",
        category="mandibular angle and ramus",
        section=LOCK_24,
        layouts=[(f"{n}h", evenly(n, 8.0)) for n in (12, 16)],
        preform=(("turn", 3, 6, 60.0),),
        material_id="cp-ti-grade-4",
        load_bearing=True,
        sources=(SRC_LOCK, SRC_NOTCH),
        notes=(
            "Turns 60 degrees in its own plane (a 120 degree gonial angle) "
            "between the ramus and the body; the bone face stays flat on the "
            "lateral surface through the turn."
        ),
        marking=("Ti4", "2.4", "ANG"),
        code="AN24",
    ),
    Family(
        family="generic-recon-2.8-hemi",
        name="Hemimandibular reconstruction plate, 2.8 mm profile, 5 + 17",
        category="hemimandibular",
        section=HEAVY_28,
        layouts=[("22h", evenly(22, 9.0))],
        preform=(("turn", 4, 6, 60.0), ("arch", 12, 21, 55.0)),
        material_id="cp-ti-grade-4",
        load_bearing=True,
        sources=(SRC_HEAVY, SRC_NOTCH),
        min_bend_radius_mm=15.0,
        notes=(
            "Ramus (5 holes), the gonial angle, and the body toward the "
            "symphysis (17 holes), preformed. Shape any further by press."
        ),
        marking=("Ti4", "2.8", "HEM"),
        code="HM28",
    ),
    Family(
        family="generic-recon-2.4-full",
        name="Full mandibular reconstruction plate 2.4, 6 + 13 + 6",
        category="full mandibular",
        section=LOCK_24,
        layouts=[("25h", evenly(25, 8.0))],
        preform=(("turn", 5, 7, 60.0), ("arch", 7, 17, 150.0), ("turn", 17, 19, 60.0)),
        material_id="cp-ti-grade-4",
        load_bearing=True,
        sources=(SRC_LOCK, SRC_HEAVY, SRC_NOTCH),
        notes=(
            "Both rami, both angles and the whole arch, preformed: 6 + 13 + 6 "
            "holes with the arch curved through the thickness and each angle "
            "turned in the plate's own plane."
        ),
        marking=("Ti4", "2.4", "FUL"),
        code="FL24",
    ),
)


# -- meshing ----------------------------------------------------------------


def _face(outer: np.ndarray, holes: list[np.ndarray], z: float):
    """Constrained Delaunay of one face, with a fine interior point grid."""
    lo, hi = outer.min(axis=0), outer.max(axis=0)
    gx_step, gy_step = FACE_GRID_MM
    xs = np.arange(lo[0] + gx_step / 2, hi[0], gx_step)
    ys = np.arange(lo[1] + gy_step / 2, hi[1], gy_step)
    gx, gy = np.meshgrid(xs, ys)
    gx = gx + (np.arange(len(ys))[:, None] % 2) * gx_step / 2
    candidates = np.column_stack([gx.ravel(), gy.ravel()])
    margin = 0.22
    keep = point_in_polygon(candidates, outer)
    d_edge = np.min(np.linalg.norm(candidates[:, None] - outer[None], axis=2), axis=1)
    keep &= d_edge > margin
    for loop in holes:
        centre = loop.mean(axis=0)
        radius = float(np.linalg.norm(loop[0] - centre))
        keep &= np.linalg.norm(candidates - centre, axis=1) > radius + margin
    points2 = np.vstack([outer, *holes, candidates[keep]])

    vtk_points = vtk.vtkPoints()
    vtk_points.SetData(
        numpy_to_vtk(np.column_stack([points2, np.zeros(len(points2))]), deep=True)
    )
    constraints = vtk.vtkPolyData()
    constraints.SetPoints(vtk_points)
    polys = vtk.vtkCellArray()
    polys.InsertNextCell(len(outer))
    for i in range(len(outer)):  # counter-clockwise: keep the inside
        polys.InsertCellPoint(i)
    start = len(outer)
    for loop in holes:  # clockwise: cut out
        polys.InsertNextCell(len(loop))
        for i in reversed(range(start, start + len(loop))):
            polys.InsertCellPoint(i)
        start += len(loop)
    constraints.SetPolys(polys)

    cloud = vtk.vtkPolyData()
    cloud.SetPoints(vtk_points)
    delaunay = vtk.vtkDelaunay2D()
    delaunay.SetInputData(cloud)
    delaunay.SetSourceData(constraints)
    delaunay.SetTolerance(1e-9)
    delaunay.Update()
    out = delaunay.GetOutput()
    if out.GetNumberOfPoints() != len(points2):
        raise RuntimeError("Delaunay merged input points; face would not close")
    triangles = vtk_to_numpy(out.GetPolys().GetConnectivityArray()).reshape(-1, 3)
    return np.column_stack([points2, np.full(len(points2), z)]), triangles


def _ring_strip(ring_count: int, per_ring: int, base: int) -> list[tuple[int, int, int]]:
    tris = []
    for j in range(ring_count - 1):
        a, b = base + j * per_ring, base + (j + 1) * per_ring
        for k in range(per_ring):
            k2 = (k + 1) % per_ring
            tris.append((a + k, a + k2, b + k2))
            tris.append((a + k, b + k2, b + k))
    return tris


def flat_solid(shape: PlateShape) -> tuple[np.ndarray, np.ndarray]:
    """The unbent plate as a watertight, outward-oriented triangle mesh."""
    t = shape.thickness_mm
    top, bottom = t / 2.0, -t / 2.0
    r = shape.edge_radius_mm
    rings: list[tuple[float, float]] = []
    for phi in np.linspace(0.0, math.pi / 2.0, 4):
        rings.append((r - r * math.sin(phi), top - r + r * math.cos(phi)))
    for phi in np.linspace(math.pi / 2.0, 0.0, 4):
        rings.append((r - r * math.sin(phi), bottom + r - r * math.cos(phi)))
    rings = [ring for i, ring in enumerate(rings) if i == 0 or ring != rings[i - 1]]

    pieces: list[np.ndarray] = []
    tris: list[tuple[int, int, int]] = []

    def add(points, triangles):
        base = sum(len(p) for p in pieces)
        pieces.append(points)
        tris.extend((a + base, b + base, c + base) for a, b, c in triangles)

    loops = [outline(shape, inset) for inset, _ in rings]
    wall = np.vstack([np.column_stack([loop, np.full(len(loop), z)])
                      for loop, (_, z) in zip(loops, rings)])
    add(wall, _ring_strip(len(rings), len(loops[0]), 0))

    section = shape.hole.section(t)
    for x in shape.hole_x_mm:
        stack = np.vstack([
            np.column_stack([hole_loop(x, radius, HOLE_SAMPLES), np.full(HOLE_SAMPLES, z)])
            for radius, z in section
        ])
        add(stack, _ring_strip(len(section), HOLE_SAMPLES, 0))

    add(*_face(loops[0], [hole_loop(x, section[0][0], HOLE_SAMPLES)
                          for x in shape.hole_x_mm], top))
    add(*_face(loops[-1], [hole_loop(x, section[-1][0], HOLE_SAMPLES)
                           for x in shape.hole_x_mm], bottom))

    points = np.vstack(pieces)
    triangles = np.array(tris, dtype=np.int64)
    # Weld the seams, where faces meet walls vertex for vertex.
    keys = np.round(points / 1e-7).astype(np.int64)
    _, first, inverse = np.unique(keys, axis=0, return_index=True, return_inverse=True)
    points, triangles = points[first], inverse.reshape(-1)[triangles]
    good = (
        (triangles[:, 0] != triangles[:, 1])
        & (triangles[:, 1] != triangles[:, 2])
        & (triangles[:, 0] != triangles[:, 2])
    )
    return _orient(points, triangles[good])


def _orient(points: np.ndarray, triangles: np.ndarray):
    """Consistent, outward winding, proved rather than assumed.

    vtkPolyDataNormals with ConsistencyOn left a thousand directed edges in
    conflict on these meshes, which made the signed volume depend on where the
    plate sat. orient_outward walks the face adjacency instead.
    """
    return points, orient_outward(points, triangles)


# -- preforming --------------------------------------------------------------


def _rotate(v, axis, angle):
    axis = axis / np.linalg.norm(axis)
    return (v * math.cos(angle) + np.cross(axis, v) * math.sin(angle)
            + axis * float(np.dot(axis, v)) * (1.0 - math.cos(angle)))


def preform_stations(hole_x, program):
    """Where each hole ends up on a preformed plate, and its face normal.

    Walks along the plate integrating the preform's curvature: an ``arch``
    segment curls the plate through its thickness toward the bone, a ``turn``
    segment turns it in its own plane.
    """
    xs = np.asarray(hole_x, dtype=float)
    n = len(xs)
    rates = []
    for kind, first, last, degrees in program:
        first %= n
        last %= n
        u0, u1 = xs[first], xs[last]
        rates.append((kind, u0, u1, math.radians(degrees) / max(u1 - u0, 1e-9)))

    step = 0.05
    position = np.zeros(3)
    tangent, width, up = np.array([1.0, 0, 0]), np.array([0, 1.0, 0]), np.array([0, 0, 1.0])
    stations, normals = [position.copy()], [up.copy()]
    u = xs[0]
    for target in xs[1:]:
        while u < target - 1e-12:
            du = min(step, target - u)
            mid = u + du / 2.0
            for kind, u0, u1, rate in rates:
                if u0 <= mid <= u1:
                    angle = rate * du
                    if kind == "arch":
                        # Curl toward the bone: the tangent swings toward -up.
                        tangent = _rotate(tangent, width, angle)
                        up = _rotate(up, width, angle)
                    else:
                        tangent = _rotate(tangent, up, angle)
                        width = _rotate(width, up, angle)
            position = position + tangent * du
            u += du
        stations.append(position.copy())
        normals.append(up.copy())
    return np.array(stations), np.array(normals)


# -- marking -----------------------------------------------------------------


def marking_anchors(shape: PlateShape, tokens, height_mm: float = 0.9):
    """Short tokens laid into the solid face runs beside the screw seats."""
    if not tokens:
        return []
    anchors = []
    slots = [s for s in marking_slots(shape, height_mm) if s[1] - s[0] >= 1.8]
    for token, (x0, x1, y) in zip(tokens, slots):
        anchors.append({
            "text": token,
            "origin": [x0 + 0.15, y, shape.thickness_mm / 2.0],
            "along": [1.0, 0.0, 0.0],
            "outward": [0.0, 0.0, 1.0],
            "height_mm": height_mm,
            "max_length_mm": round(x1 - x0 - 0.3, 4),
        })
    return anchors


# -- output --------------------------------------------------------------------


def write_ply(path: Path, points: np.ndarray, triangles: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "ply\nformat binary_little_endian 1.0\n"
        "comment generic plate asset, units mm, generated by make_plate_assets.py\n"
        f"element vertex {len(points)}\n"
        "property float x\nproperty float y\nproperty float z\n"
        f"element face {len(triangles)}\n"
        "property list uchar int vertex_indices\nend_header\n"
    ).encode("ascii")
    faces = np.zeros(len(triangles), dtype=[("n", "u1"), ("i", "<i4", 3)])
    faces["n"] = 3
    faces["i"] = triangles
    with path.open("wb") as handle:
        handle.write(header)
        handle.write(points.astype("<f4").tobytes())
        handle.write(faces.tobytes())


def build(family: Family, suffix: str, hole_x):
    s = family.section
    xs = np.asarray(hole_x, dtype=float)
    gaps = np.diff(xs)
    # Any gap longer than the pitch is a bridge: the narrow bar runs the whole
    # way across it, so its notch opens nearly the full gap.
    overrides = tuple(
        (i, NotchSpec(s.notch.depth_mm, float(g - (s.pitch_mm - s.notch.opening_mm))))
        for i, g in enumerate(gaps)
        if g > s.pitch_mm + 1e-6
    )
    shape = PlateShape(
        hole_x_mm=tuple(hole_x),
        width_mm=s.width_mm,
        thickness_mm=s.thickness_mm,
        hole=s.hole,
        notch=s.notch,
        edge_radius_mm=s.edge_radius_mm,
        gap_notches=overrides,
    )
    shape.validate()
    points, triangles = flat_solid(shape)
    xs = np.asarray(shape.hole_x_mm)
    holes = np.column_stack([xs, np.zeros(len(xs)), np.zeros(len(xs))])
    axes = np.tile([0.0, 0.0, 1.0], (len(xs), 1))

    anchors = marking_anchors(shape, family.marking + (f"{len(xs)}H",) if family.marking else ())
    if family.preform:
        stations, normals = preform_stations(xs, family.preform)
        extra = []
        for anchor in anchors:
            o = np.asarray(anchor["origin"])
            extra.extend([o, o + np.array([0.5, 0, 0]), o + np.array([0, 0, 0.5])])
        extra = np.array(extra).reshape(-1, 3)
        bent = bend_to_path(
            np.vstack([points, extra]), triangles, holes, axes, stations, normals,
            protected_radius_mm=s.hole.seat_diameter_mm / 2.0 + 0.5,
            min_bend_radius_mm=0.0, max_bend_deg_per_node=180.0,
        )
        points = bent.points[: len(points)]
        moved = bent.points[len(bent.points) - len(extra):]
        for k, anchor in enumerate(anchors):
            o, a, n = moved[3 * k], moved[3 * k + 1], moved[3 * k + 2]
            anchor["origin"] = o.tolist()
            anchor["along"] = ((a - o) / np.linalg.norm(a - o)).tolist()
            anchor["outward"] = ((n - o) / np.linalg.norm(n - o)).tolist()
        holes, axes = bent.hole_centres, bent.hole_axes
    # Express the asset in its own frame at the middle hole: origin at that
    # hole's centre, +x along the plate, +z out of the outer face.
    mid = len(holes) // 2
    lo, hi = max(mid - 1, 0), min(mid + 1, len(holes) - 1)
    along = holes[hi] - holes[lo]
    face = axes[mid] / np.linalg.norm(axes[mid])
    along = along - np.dot(along, face) * face
    along /= np.linalg.norm(along)
    frame = np.vstack([along, np.cross(face, along), face])  # rows: new x, y, z
    origin = holes[mid].copy()

    def local(v, is_point=True):
        v = np.asarray(v, dtype=float)
        return ((v - origin) if is_point else v) @ frame.T

    points = local(points)
    holes = local(holes)
    axes = local(axes, is_point=False)
    for anchor in anchors:
        anchor["origin"] = local(anchor["origin"]).round(6).tolist()
        anchor["along"] = local(anchor["along"], False).round(9).tolist()
        anchor["outward"] = local(anchor["outward"], False).round(9).tolist()
    return shape, points, triangles, holes, axes, anchors


def entry(family: Family, suffix: str, shape, points, triangles, holes, axes, anchors, audit):
    s = family.section
    lo, hi = points.min(axis=0), points.max(axis=0)
    count = len(holes)
    return {
        "id": f"{family.family}-{suffix}",
        "name": f"{family.name}, {count} holes" + (" (bridged)" if "bridge" in suffix else ""),
        "family": family.family,
        "category": family.category,
        "exact": False,
        "generic": True,
        "status_label": "Generic parametric approximation",
        "notice": GENERIC_NOTICE,
        "mesh": f"{family.family}-{suffix}.ply",
        "mesh_format": "ply",
        "units": "mm",
        "unit_scale": 1.0,
        "coordinate_convention": (
            "+z out of the outer face at the middle hole, the plate running "
            "along +x there; origin at the middle hole's centre"
        ),
        "thickness_mm": s.thickness_mm,
        "width_mm": s.width_mm,
        "hole_count": count,
        "hole_pitch_mm": s.pitch_mm,
        "hole_diameter_mm": s.hole.bore_diameter_mm,
        "seat_diameter_mm": s.hole.seat_diameter_mm,
        "locking": s.hole.locking,
        "thread_pitch_mm": s.hole.thread_pitch_mm if s.hole.locking else None,
        "notch": {"depth_mm": s.notch.depth_mm, "opening_mm": s.notch.opening_mm},
        "edge_radius_mm": s.edge_radius_mm,
        "length_mm": round(shape.length_mm, 4),
        "extent_mm": round(float((hi - lo).max()), 4),
        "flat_hole_x_mm": [round(float(x), 6) for x in shape.hole_x_mm],
        "hole_centres_mm": np.round(holes, 6).tolist(),
        "hole_axes": np.round(axes, 9).tolist(),
        "centreline_mm": np.round(holes, 6).tolist(),
        "side": "universal",
        "mirrorable": True,
        "preform": [list(step) for step in family.preform],
        "material_id": family.material_id,
        "load_bearing": family.load_bearing,
        "dimension_sources": list(family.sources),
        "deformation": {
            "min_bend_radius_mm": family.min_bend_radius_mm,
            "max_bend_deg_per_node": (
                family.max_bend_deg_per_node
                if family.max_bend_deg_per_node is not None
                else working_bend_limit(s, s.pitch_mm, family.material_id)
            ),
            "protected_radius_mm": round(s.hole.seat_diameter_mm / 2.0 + 0.5, 4),
            "bendable": "at the notches between holes",
        },
        "marking": anchors,
        "code": f"{family.code}-{suffix.upper()}",
        "provenance": PROVENANCE,
        "licence": LICENCE,
        "audit": audit,
        "notes": family.notes,
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUT_DIR)
    parser.add_argument("--family", default=None)
    args = parser.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)

    entries, failures = [], []
    for family in FAMILIES:
        if args.family and family.family != args.family:
            continue
        for suffix, hole_x in family.layouts:
            shape, points, triangles, holes, axes, anchors = build(family, suffix, hole_x)
            mesh = Mesh(points, triangles)
            audit = {
                "watertight": bool(mesh.is_watertight()),
                "outward": bool(mesh.is_outward()),
                "genus": int(mesh.genus()),
                "triangles": int(len(triangles)),
                "points": int(len(points)),
                "volume_mm3": round(float(mesh.volume_mm3()), 4),
            }
            name = f"{family.family}-{suffix}"
            write_ply(args.out / f"{name}.ply", points, triangles)
            entries.append(entry(family, suffix, shape, points, triangles, holes, axes, anchors, audit))
            ok = audit["watertight"] and audit["outward"] and audit["genus"] == len(holes)
            if not ok:
                failures.append(name)
            print(f"  {'ok ' if ok else 'BAD'} {name:<36} {audit['triangles']:>6} tris  "
                  f"genus {audit['genus']:>2}/{len(holes):<2} {shape.length_mm:6.1f} mm")

    if not args.family:
        for stale in args.out.glob("generic-*.stl"):
            stale.unlink()
    catalogue = {
        "note": [
            "Generic plate assets generated in this repository from published",
            "dimensional classes; see each entry's dimension_sources.",
            GENERIC_NOTICE,
            "No manufacturer CAD, part number or trade dress is used or implied.",
            "To add a licensed exact asset, drop its mesh and an entry here; set",
            "exact to true only when provenance and licence genuinely support it.",
        ],
        "generated_by": "tools/make_plate_assets.py",
        "plates": entries,
    }
    (args.out / "plates.json").write_text(json.dumps(catalogue, indent=2) + "\n", encoding="utf-8")
    print(f"\n{len(entries)} assets -> {args.out}")
    if failures:
        print(f"FAILED: {failures}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
